# Generated by Django 5.1.7 on 2025-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Системная'), ('light', 'Светлая'), ('dark', 'Тёмная')], default='system', max_length=10),
        ),
    ]
