# Generated by Django 5.1.7 on 2025-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_emailschedule_updated_at_emailclientconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Один раз'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='once', max_length=10),
        ),
    ]
