# Generated by Django 5.1.7 on 2025-03-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_emailschedule_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='scheduler.emailschedule')),
            ],
        ),
    ]
